server:
  port: 8101

eureka:
  instance:
    hostname: localhost
  client:
    # 不是用eureka进行服务注册
    register-with-eureka: false
    # 不在本地缓存注册信息w
    fetch-registry: false
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
#      defaultZone: http://localhost:8101/eureka/,http://localhost:8102/eureka/  #8100
      defaultZone: http://localhost:8100/eureka/,http://localhost:8102/eureka/  #8101
#      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/  #8102
  server:
    # 在服务器接收请求之前等待初始时间
    wait-time-in-ms-when-sync-empty: 5
    enable-self-preservation: false
spring:
  application:
    name: eureka-server

