eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/,http://localhost:8102/eureka/
server:
  port: 8301
spring:
  application:
    name: ribbon-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

